[[colors.indexed_colors]]
color = "#f7768e"
index = 16

[[colors.indexed_colors]]
color = "#ff9e64"
index = 17

[colors.cursor]
cursor = "#7aa2f7"
text = "#1a1b26"

[colors.footer_bar]
background = "#7aa2f7"
foreground = "#1a1b26"

[colors.hints.end]
background = "#7aa2f7"
foreground = "#1a1b26"

[colors.hints.start]
background = "#7aa2f7"
foreground = "#1a1b26"

[colors.primary]
background = "#1a1b26"
bright_foreground = "#c0caf5"
dim_foreground = "#414868"
foreground = "#c0caf5"

[colors.search.focused_match]
background = "#7aa2f7"
foreground = "#1a1b26"

[colors.search.matches]
background = "#9ece6a"
foreground = "#1a1b26"

[colors.selection]
background = "#9ece6a"
text = "#1a1b26"

[colors.vi_mode_cursor]
cursor = "#7aa2f7"
text = "#1a1b26"

[font]
size = 6.5

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[window]
opacity = 0.95

[window.padding]
x = 10
y = 10
