#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

systemctl --user import-environment DISPLAY XAUTHORITY
systemctl --user restart xdg-desktop-portal xdg-desktop-portal-gtk &

wal -R &
sleep 0.5

wal_normal=$(xrdb -query | awk '/\*color8:/ {print $2}')
wal_focused=$(xrdb -query | awk '/\*color4:/ {print $2}')

: "${wal_normal:=#414868}"
: "${wal_focused:=#7aa2f7}"  

bspc config border_width          1
bspc config window_gap            3
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config normal_border_color "$wal_normal"
bspc config focused_border_color "$wal_focused"
bspc config active_border_color  "$wal_focused"

polybar &
picom --config "$HOME/.config/picom/picom.conf" &
dunst &
libinput-gestures &
xsetroot -cursor_name left_ptr &
