#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# bspc config focused_border_color "#7aa2f7"
# bspc config normal_border_color "#2e3a49"

bspc config normal_border_color "#414868"
bspc config focused_border_color "#7aa2f7"
bspc config active_border_color "#7aa2f7"

bspc config border_width        2
bspc config window_gap          2

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

#Auto start apps
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
libinput-gestures &
xsetroot -cursor_name left_ptr
